
name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Build Project
        run: |
          npm install
          npm run build

  deploy:
    name: deploy to server
    needs: [build]

    runs-on: ubuntu-latest

    steps:
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: premium700.web-hosting.com
          username: ${{ secrets.REACT_FTP_USERNAME }}
          password: ${{ secrets.REACT_FTP_PASSWORD }}
