
name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.khushab.co.uk
          username: ${{ secrets.REACT_FTP_USERNAME }}
          password: ${{ secrets.REACT_FTP_PASSWORD }}
